services:
    mongodb:
        image: mongo:latest
        container_name: mongodb_download_yt
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
        ports:
            - "${MONGODB_PORT}:27017"
        volumes:
            - mongodb_data:/data/db
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
            interval: 10s
            timeout: 10s
            retries: 5
            start_period: 40s
        networks:
            - app_network

    api:
        build: .
        container_name: api_download_yt
        restart: always
        ports:
            - "${PORT}:${PORT}"
        volumes:
            - .:/usr/src/app:cached
            - /usr/src/app/node_modules
        develop:
            watch:
                - path: .
                  target: /usr/src/app
                  ignore:
                      - node_modules/
                      - dist/
                  action: sync
        environment:
            - NODE_ENV=development
            - TYPESCRIPT_NODE_COMPILER_OPTIONS={"module":"commonjs"}
        depends_on:
            mongodb:
                condition: service_healthy
        networks:
            - app_network

networks:
    app_network:
        driver: bridge

volumes:
    mongodb_data:
